# fly.toml file generated for naskyai-app on 2024-08-25T11:47:00+00:00

app = 'naskyai-app'
primary_region = 'sin'

[build]
  builder = 'paketobuildpacks/builder-jammy-base'
  buildpacks = ['gcr.io/paketo-buildpacks/python', 'gcr.io/paketo-buildpacks/nodejs']

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']
